version: '4.21.1'
services:
  app:  
    build: .
    volumes:
      - .:/model_backend
    image: model_backend:latest
    ports:
      - 8000:8000
    container_name: model_container
    command: gunicorn -w 4 -b :8000 app:app

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app